import { useState } from 'react';
import {
	AlertTriangle,
	ChevronDown,
	ChevronRight,
	FileText,
	ShieldAlert,
	ShieldCheck,
	Clock,
	Stethoscope,
} from 'lucide-react';

const RiskBadge = ({ level }) => {
	const styles = {
		Low: 'bg-emerald-50 text-emerald-700 border-emerald-200',
		Medium: 'bg-amber-50 text-amber-700 border-amber-200',
		High: 'bg-orange-50 text-orange-700 border-orange-200',
		Critical: 'bg-red-50 text-red-700 border-red-200',
	};
	return (
		<span
			className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold border ${styles[level] || styles.Medium}`}
		>
			{level}
		</span>
	);
};

const BoolBadge = ({
	value,
	trueLabel = 'Yes',
	falseLabel = 'No',
	invertColor = false,
}) => {
	const isTrue = invertColor ? !value : value;
	return (
		<span
			className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${
				isTrue
					? 'bg-red-50 text-red-600 border border-red-200'
					: 'bg-emerald-50 text-emerald-600 border border-emerald-200'
			}`}
		>
			{value ? trueLabel : falseLabel}
		</span>
	);
};

/* ─── Cross-Report Analysis Card ─── */
const CrossReportCard = ({ crossReport }) => {
	if (!crossReport) return null;

	return (
		<div className="bg-white/60 backdrop-blur-sm rounded-xl border border-white/70 overflow-hidden">
			<div className="px-4 py-3 bg-amber-50/50 border-b border-amber-100">
				<div className="flex items-center gap-2">
					<ShieldAlert className="w-4 h-4 text-amber-600" />
					<h3 className="text-sm font-semibold text-primary80">
						Cross-Report Analysis
					</h3>
					<BoolBadge
						value={crossReport.isLikelyFabricatedBySingleAgency}
						trueLabel="Likely Fabricated"
						falseLabel="No Fabrication Detected"
					/>
				</div>
				<p className="text-xs text-primary40 mt-0.5 ml-6">
					Compares values across all reports to detect if multiple reports
					were generated by the same fraudulent source
				</p>
			</div>
			<div className="px-4 py-3 space-y-2">
				{crossReport.explanation && (
					<p className="text-sm text-primary60">
						{crossReport.explanation}
					</p>
				)}
				{crossReport.sharedAnomalies?.length > 0 && (
					<div>
						<p className="text-xs font-medium text-primary40 mb-1">
							Shared Anomalies:
						</p>
						<div className="flex flex-wrap gap-1.5">
							{crossReport.sharedAnomalies.map((a, i) => (
								<span
									key={i}
									className="px-2 py-0.5 bg-amber-50 text-amber-700 text-xs rounded-md border border-amber-200"
								>
									{a}
								</span>
							))}
						</div>
					</div>
				)}
			</div>
		</div>
	);
};

/* ─── Test Results Table ─── */
const TestResultsTable = ({ results }) => {
	if (!results?.length) return null;

	const redFlagCount = results.filter((r) => r.isRedFlag).length;

	return (
		<div className="mt-3">
			<div className="flex items-center gap-2 mb-2">
				<p className="text-xs font-medium text-primary40">
					{results.length} test(s) extracted
				</p>
				{redFlagCount > 0 && (
					<span className="px-1.5 py-0.5 bg-red-50 text-red-600 text-xs font-medium rounded border border-red-200">
						{redFlagCount} red flag{redFlagCount > 1 ? 's' : ''}
					</span>
				)}
			</div>
			<div className="overflow-x-auto rounded-lg border border-gray-100">
				<table className="w-full text-xs">
					<thead>
						<tr className="bg-gray-50/80">
							<th className="px-3 py-2 text-left font-medium text-primary40">
								Test Name
							</th>
							<th className="px-3 py-2 text-center font-medium text-primary40">
								Result
							</th>
							<th className="px-3 py-2 text-center font-medium text-primary40">
								Unit
							</th>
							<th className="px-3 py-2 text-center font-medium text-primary40">
								Report Range
							</th>
							<th className="px-3 py-2 text-center font-medium text-primary40">
								Standard Range
							</th>
							<th className="px-3 py-2 text-center font-medium text-primary40">
								Flag
							</th>
						</tr>
					</thead>
					<tbody>
						{results.map((test, i) => (
							<tr
								key={i}
								className={`border-t border-gray-50 ${
									test.isRedFlag ? 'bg-red-50/30' : ''
								}`}
							>
								<td className="px-3 py-1.5 text-primary80 font-medium">
									{test.testName}
								</td>
								<td
									className={`px-3 py-1.5 text-center font-mono ${
										test.isRedFlag
											? 'text-red-600 font-semibold'
											: 'text-primary60'
									}`}
								>
									{test.resultValue}
								</td>
								<td className="px-3 py-1.5 text-center text-primary40">
									{test.unit}
								</td>
								<td className="px-3 py-1.5 text-center text-primary40">
									{test.reportReferenceRange}
								</td>
								<td className="px-3 py-1.5 text-center text-primary40">
									{test.standardReferenceRange}
								</td>
								<td className="px-3 py-1.5 text-center">
									{test.isRedFlag ? (
										<span
											className="text-red-500"
											title={test.flagReason}
										>
											&#9888;
										</span>
									) : (
										<span className="text-emerald-500">
											&#10003;
										</span>
									)}
								</td>
							</tr>
						))}
					</tbody>
				</table>
			</div>
		</div>
	);
};

/* ─── Single Report Card (Expandable) ─── */
const ReportCard = ({ report, index }) => {
	const [expanded, setExpanded] = useState(false);
	const forensic = report.forensicAnalysis || {};
	const medical = report.medicalConsistency || {};
	const temporal = forensic.temporalCheck || {};
	const redFlags = (report.detailedResults || []).filter(
		(r) => r.isRedFlag,
	).length;

	return (
		<div className="bg-white/60 backdrop-blur-sm rounded-xl border border-white/70 overflow-hidden">
			{/* Header — always visible */}
			<button
				onClick={() => setExpanded(!expanded)}
				className="w-full flex items-center gap-3 px-4 py-3 hover:bg-white/40 transition-colors text-left"
			>
				<FileText className="w-4 h-4 text-purple-100 shrink-0" />
				<div className="flex-1 min-w-0">
					<div className="flex items-center gap-2">
						<p className="text-sm font-semibold text-primary80 truncate">
							{report.labName || `Report ${index + 1}`}
						</p>
						{report.reportRefNumber && (
							<span className="text-xs text-primary40">
								#{report.reportRefNumber}
							</span>
						)}
					</div>
					<div className="flex items-center gap-3 text-xs text-primary40 mt-0.5">
						{report.patientName && <span>{report.patientName}</span>}
						{report.reportDate && (
							<span className="flex items-center gap-1">
								<Clock className="w-3 h-3" />
								{report.reportDate}
							</span>
						)}
						<span>{(report.detailedResults || []).length} tests</span>
						{redFlags > 0 && (
							<span className="text-red-500 font-medium">
								{redFlags} red flag{redFlags > 1 ? 's' : ''}
							</span>
						)}
					</div>
				</div>
				<div className="flex items-center gap-2 shrink-0">
					{forensic.isLikelyTampered && (
						<BoolBadge value={true} trueLabel="Tampered" />
					)}
					{!medical.isConsistent && (
						<span className="px-2 py-0.5 bg-amber-50 text-amber-600 text-xs font-medium rounded-full border border-amber-200">
							Inconsistent
						</span>
					)}
					{expanded ? (
						<ChevronDown className="w-4 h-4 text-primary40" />
					) : (
						<ChevronRight className="w-4 h-4 text-primary40" />
					)}
				</div>
			</button>

			{/* Expanded detail */}
			{expanded && (
				<div className="px-4 pb-4 border-t border-gray-100 space-y-3">
					{/* Forensic + Medical + Temporal row */}
					<div className="grid grid-cols-3 gap-3 pt-3">
						{/* Forensic */}
						<div className="bg-gray-50/80 rounded-lg p-3 space-y-1">
							<div className="flex items-center gap-1.5">
								<ShieldAlert className="w-3.5 h-3.5 text-amber-500" />
								<p className="text-xs font-semibold text-primary60">
									Forensic Analysis
								</p>
							</div>
							<p className="text-[10px] text-primary30 -mt-0.5">
								Checks for signs of tampering or fabrication in this
								report
							</p>
							<div className="flex items-center gap-2">
								<BoolBadge
									value={forensic.isLikelyTampered}
									trueLabel="Tampered"
									falseLabel="Clean"
								/>
								{forensic.confidenceScore != null && (
									<span className="text-xs text-primary40">
										{Math.round(forensic.confidenceScore * 100)}%
										confidence
									</span>
								)}
							</div>
							{forensic.explanation && (
								<p className="text-xs text-primary40 line-clamp-3">
									{forensic.explanation}
								</p>
							)}
						</div>

						{/* Temporal */}
						<div className="bg-gray-50/80 rounded-lg p-3 space-y-1">
							<div className="flex items-center gap-1.5">
								<Clock className="w-3.5 h-3.5 text-blue-500" />
								<p className="text-xs font-semibold text-primary60">
									Temporal Check
								</p>
							</div>
							<p className="text-[10px] text-primary30 -mt-0.5">
								Verifies if sample collection and report dates are
								realistic
							</p>
							<BoolBadge
								value={temporal.isPlausible}
								trueLabel="Plausible"
								falseLabel="Suspicious"
								invertColor={true}
							/>
							{temporal.explanation && (
								<p className="text-xs text-primary40 line-clamp-3">
									{temporal.explanation}
								</p>
							)}
						</div>

						{/* Medical Consistency */}
						<div className="bg-gray-50/80 rounded-lg p-3 space-y-1">
							<div className="flex items-center gap-1.5">
								<Stethoscope className="w-3.5 h-3.5 text-emerald-500" />
								<p className="text-xs font-semibold text-primary60">
									Medical Consistency
								</p>
							</div>
							<p className="text-[10px] text-primary30 -mt-0.5">
								Checks if abnormal values make medical sense together
							</p>
							<BoolBadge
								value={medical.isConsistent}
								trueLabel="Consistent"
								falseLabel="Inconsistent"
								invertColor={true}
							/>
							{medical.findings?.length > 0 && (
								<p className="text-xs text-primary40 line-clamp-3">
									{medical.findings.join('; ')}
								</p>
							)}
						</div>
					</div>

					{/* Test Results Table */}
					<TestResultsTable results={report.detailedResults} />
				</div>
			)}
		</div>
	);
};

/* ─── Main Component ─── */
const AnalysisReport = ({ analysis }) => {
	if (!analysis) return null;

	const reports = analysis.reports || [];
	const crossReport = analysis.crossReportAnalysis;

	return (
		<div className="space-y-4 mt-6">
			<div>
				<h2 className="text-sm font-semibold text-primary80 uppercase tracking-wider">
					Detailed Analysis
				</h2>
				<p className="text-xs text-primary40 mt-0.5">
					AI-generated forensic breakdown — cross-report fraud detection,
					per-report tampering assessment, and individual test results
				</p>
			</div>

			{/* Cross-report card */}
			<CrossReportCard crossReport={crossReport} />

			{/* Per-report cards */}
			{reports.length > 0 && (
				<div className="space-y-3">
					<p className="text-xs font-medium text-primary40">
						{reports.length} report{reports.length > 1 ? 's' : ''}{' '}
						analyzed
					</p>
					{reports.map((report, i) => (
						<ReportCard key={i} report={report} index={i} />
					))}
				</div>
			)}
		</div>
	);
};

export default AnalysisReport;
